
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.p1;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION = 39;
  public static final int l_SANTA = 30;
  public static final int FINREGALO = 52;
  public static final int HADA = 41;
  public static final int PERSONA = 19;
  public static final int CIERRACUENTO = 32;
  public static final int DANCER = 6;
  public static final int DUENDE = 42;
  public static final int ENTREGA = 48;
  public static final int CIERRAREGALO = 36;
  public static final int ABREEMPAQUE = 33;
  public static final int RODOLFO = 2;
  public static final int FATHER_CHRISTMAS = 20;
  public static final int CIERRAEMPAQUE = 34;
  public static final int l_SANTA_CLAUS = 27;
  public static final int l_PAPA_NOEL = 28;
  public static final int l_SAN_NICOLAS = 29;
  public static final int NARRA = 50;
  public static final int l_FFATHER_CHRISTMAS = 25;
  public static final int HACE = 44;
  public static final int MAIN = 37;
  public static final int l_TFATHER_CHRISTMAS = 26;
  public static final int ENVUELVE = 43;
  public static final int COMETA = 4;
  public static final int SANTA_CLAUS = 21;
  public static final int PAPA_NOEL = 22;
  public static final int TURENO = 3;
  public static final int SAN_NICOLAS = 23;
  public static final int GRINCH = 9;
  public static final int EOF = 0;
  public static final int CORTA = 47;
  public static final int MELCHOR = 16;
  public static final int REVISA = 45;
  public static final int error = 1;
  public static final int GASPAR = 17;
  public static final int ABRECUENTO = 31;
  public static final int SNOWBALL = 10;
  public static final int PEPPER = 12;
  public static final int ESCUCHA = 51;
  public static final int ABREREGALO = 35;
  public static final int PRANCER = 7;
  public static final int DASHER = 5;
  public static final int ENVIA = 46;
  public static final int SHINNY = 14;
  public static final int BALTAZAR = 18;
  public static final int BUSHY = 11;
  public static final int SUGARPLUM = 13;
  public static final int SANTA = 24;
  public static final int ELFO = 40;
  public static final int LOCAL = 38;
  public static final int WUNORSE = 15;
  public static final int QUIEN = 8;
  public static final int BASTON = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RODOLFO",
  "TURENO",
  "COMETA",
  "DASHER",
  "DANCER",
  "PRANCER",
  "QUIEN",
  "GRINCH",
  "SNOWBALL",
  "BUSHY",
  "PEPPER",
  "SUGARPLUM",
  "SHINNY",
  "WUNORSE",
  "MELCHOR",
  "GASPAR",
  "BALTAZAR",
  "PERSONA",
  "FATHER_CHRISTMAS",
  "SANTA_CLAUS",
  "PAPA_NOEL",
  "SAN_NICOLAS",
  "SANTA",
  "l_FFATHER_CHRISTMAS",
  "l_TFATHER_CHRISTMAS",
  "l_SANTA_CLAUS",
  "l_PAPA_NOEL",
  "l_SAN_NICOLAS",
  "l_SANTA",
  "ABRECUENTO",
  "CIERRACUENTO",
  "ABREEMPAQUE",
  "CIERRAEMPAQUE",
  "ABREREGALO",
  "CIERRAREGALO",
  "MAIN",
  "LOCAL",
  "FUNCTION",
  "ELFO",
  "HADA",
  "DUENDE",
  "ENVUELVE",
  "HACE",
  "REVISA",
  "ENVIA",
  "CORTA",
  "ENTREGA",
  "BASTON",
  "NARRA",
  "ESCUCHA",
  "FINREGALO"
  };
}

