
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.p1;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int PRIVATE = 11;
  public static final int SEMI = 2;
  public static final int IDENTIFIER = 12;
  public static final int LPAREN = 7;
  public static final int PUBLIC = 10;
  public static final int STRING_LITERAL = 14;
  public static final int BOOLEAN = 19;
  public static final int EOF = 0;
  public static final int NUMBER = 15;
  public static final int BREAK = 18;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 16;
  public static final int ABSTRACT = 9;
  public static final int INTEGER_LITERAL = 13;
  public static final int EQEQ = 17;
  public static final int UMINUS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "ABSTRACT",
  "PUBLIC",
  "PRIVATE",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "NUMBER",
  "EQ",
  "EQEQ",
  "BREAK",
  "BOOLEAN"
  };
}

